export const API_URL = 'http://127.0.0.1:8080/api/'
export const LOGIN_URL = API_URL + 'login/'
export const REGISTER_URL = API_URL + 'register/'
export const LOGOUT_URL = API_URL + 'logout'
export const CSRF_TOKEN_URL = API_URL + 'csrf'
export const CHECK_AUTHENTICATION = API_URL + 'auth'
export const FETCH_STATUS = API_URL + 'status/fetch'
export const FETCH_STATUS_PROFILE = API_URL + 'status/fetch/profile'
export const UPLOAD_IMAGE = API_URL + 'upload/image/'
export const POST_SUBMIT = API_URL + 'post/create/'
export const STATUS_COMMENT = API_URL + 'status/comment'
export const STATUS_FETCH_COMMENT = API_URL + 'status/comment'
export const STATUS_VOTE = API_URL + 'status/vote/'
export const FRIEND_TAGGING = API_URL + 'friend/tag'
export const PLUSTAG_VOTE = API_URL + 'status/plustag'
export const PLUSTAG_DELETE = API_URL + 'status/plustag/delete'
export const FETCH_NOTIFICATION = API_URL + 'noti/fetch'
export const FETCH_PROFILE = API_URL + 'profile/fetch'
export const FETCH_PROFILE_INFO = API_URL + 'profile/info'
export const HEADER_SEARCH = API_URL + 'search/header'
export const ONLINE_FRIENDS = API_URL + 'chat/online'
export const POST_ONLINE = API_URL + 'on'
// message
export const CHAT_FRAME_INFORMATION = API_URL + 'chat/frame'
export const SUBMIT_CHAT = API_URL + 'chat/send'
export const GET_MESSAGE = API_URL + 'chat/get_mess'
export const POLL_REQUEST = API_URL + 'chat/poll'
// network
export const NETWORK_REGISTER = API_URL + 'network/register'
export const CHECK_NETWORKAUTHENTICATION = API_URL + 'netauth'
export const NETWORK_GOAL = API_URL + 'network/goal'
export const GET_NETWORK = API_URL + 'network/get'
export const GET_NETWORK_PROFILE = API_URL + 'network/profile'
// network group chatting
export const SEARCH_CHAT_TOPIC = API_URL + 'network/chatroom/search'
export const CHAT_TOPIC_CREATE = API_URL + 'network/chatroom/topic'
export const CHAT_ROOM_SETTINGS = API_URL + 'network/chatroom/settings'

// network chatting
export const NETWORK_PEOPLE = API_URL + 'network/chat/people'
export const NETWORK_FRAME = API_URL + 'network/chat/frame'
export const GET_NETWORK_MESSAGE = API_URL + 'network/chat/message'
export const SEND_NETWORK_MESSAGE = API_URL + 'network/chat/sendmessage'
export const PULL_NETWORK_MESSAGE = API_URL + 'network/chat/pull'
//
export const TAB_FOLLOWERS = API_URL + 'tab_followers'
